### ISSUE TITLE
Files in json

### ISSUE THREAD

**Issue by voidzero** [igorecarrasco/tweet_deleter#1]
Hi,

Looks like twitter is now returning a zip file with, among other things, tweet.js.

This file seems to be json or javascript. I don't know...

would you be willing to update your script to accomodate these changes?

Mark

**Comment by igorecarrasco** [comment]
Sure. Let me try importing my history again to see what the new format is, then work on it.

**Comment by attacus** [comment]
FWIW, I wrote the following script as a workaround to generate a `tweet_deleter`-compatible CSV file from the JSON that Twitter gives you. I also formatted the date differently to make it easier to sort the CSV if you only want to delete tweets in a certain date range, because I noted that the `tweet.js` file doesn't give you the data chronologically.

Put your `tweet.js` filepath in the `path` variable, and this will produce a `tweets.csv` that you can drop into the same directory as `tweet_deleter`. From there you can run `delete.py` as normal.

```
import csv
import json
from dateutil.parser import parse

path = "filename"

with open(path) as json_file:  
    x = json.load(json_file)
    

    f = csv.writer(open("tweets.csv", "w+"))

    f.writerow(["tweet_id", "created_at", "full_text"])

    for x in x:
        dt = parse(x["created_at"])
        f.writerow([x["id_str"],
                    dt,
                    x["full_text"]])
```

**Comment by voidzero** [comment]
Oh, cool, I'll test this out and will check back. Deleting old likes was another thing on my todo list by twe way. So I'll let you know. Thank you!

**Comment by attacus** [comment]
Deleting old likes with `unlike.py` should still work out of the box. It uses the Twitter API directly and doesn't take an input file.

**Comment by igorecarrasco** [comment]
I have ~maimed and tortured~ adapted the script to run on the .js file.
